// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzv_c3fpqNChVSPvy6ppXVk3qg7_W-ebg',
    appId: '1:1095908565685:web:4a0c7c38cfb03b1b5394fc',
    messagingSenderId: '1095908565685',
    projectId: 'auracle-f725b',
    authDomain: 'auracle-f725b.firebaseapp.com',
    storageBucket: 'auracle-f725b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGHsZi3qNUqJyfS2esMIT5xSuDp0I2S7c',
    appId: '1:1095908565685:android:ac8171d9a7a946d15394fc',
    messagingSenderId: '1095908565685',
    projectId: 'auracle-f725b',
    storageBucket: 'auracle-f725b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh80K0qjqzOfIYyAcaoQWPWevvhdSSx2o',
    appId: '1:1095908565685:ios:be217e14189418c15394fc',
    messagingSenderId: '1095908565685',
    projectId: 'auracle-f725b',
    storageBucket: 'auracle-f725b.firebasestorage.app',
    androidClientId: '1095908565685-qj337t9vhimmvhsic63qqeopg2ofkm76.apps.googleusercontent.com',
    iosClientId: '1095908565685-akevlq76rjq7jvn5b9hicg77nt8tvd20.apps.googleusercontent.com',
    iosBundleId: 'com.juktobit.auracle',
  );

}